Cache:
  NetWork: tcp
  Host: 127.0.0.1
  Post: 6379
  Pwd:

DB:
  AutoCreateTable: true
  DriverName: com.mysql.jdbc.Driver
  Database: cool_admin
  Url: root:zjj930716.@/cool_admin?charset=utf8&parseTime=True&loc=Local
  Username: root
  Password: zjj930716.
  Dialect: mysql

#验证
Valid:
  IsLoginValidCaptcha: false
  IsOpenAuthorization: false

#通知
Notify:
  ErrorIsOpen: false
  Email:
    FromEmail: xfzandysw@163.com
    EmailHost: smtp.163.com
    EmailPort: 465
    EmailPass: 123456
